### ISSUE TITLE
Defective code.

### ISSUE THREAD

**Issue by OGonzalezNYC** [learn-co-curriculum/map-dispatch-to-props-readme#20]
As-is, the final revision to the final line of code will break the app in the browser.  Instead of 

export default connect(state => ({ items: state.items }))(App);

it ought to be:

export default connect(state => ({ items: state.items }), {addItem})(App);

.

**Comment by Sdcrouse** [comment]
That works, but you actually _can_ use
```
export default connect(state => ({ items: state.items }))(App);
```

...provided you then change the `handleOnClick` function to look like this:
```
handleOnClick = event => {
    this.props.dispatch(addItem());
  }
```
or this:
```
handleOnClick = event => {
    this.props.dispatch({ type: 'INCREASE_COUNT' });
  }
```

But if you don't change the `handleOnClick` function, then you're right - the code will break the app in the browser.
