### ISSUE TITLE
Restaurants component calls `restaurant.restaurantName` for render - should call `restaurant.name`

### ISSUE THREAD

**Issue by mdjurdj1** [learn-co-curriculum/map-dispatch-to-props-readme#3]
Minor issue, but restaurant list won't display since the restaurant object has a `name` key and not a `restaurantName` key. (Line 8, components/Restaurants.js)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and modified this lesson to no longer use components/Restaurants.js and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
