### ISSUE TITLE
Include example with parent AND child components

### ISSUE THREAD

**Issue by meg-gutshall** [learn-co-curriculum/map-dispatch-to-props-readme#37]
In [the lab that follows this lesson](https://github.com/learn-co-curriculum/map-dispatch-to-props-lab), we're expected to know how to pass state from child components to the store when all previous lessons show code-alongs at the top-level `App` component only. It would be super helpful to have at least one example of a multi-level component application in a lesson before we see one in a lab.

**Comment by graciemcguire** [comment]
Hi @meg-gutshall we are not currently adding new content to this section of the curriculum, but thanks for your suggestion!
