### ISSUE TITLE
Code provided for lesson does not match the lesson.

### ISSUE THREAD

**Issue by B0NG0FURY** [learn-co-curriculum/map-dispatch-to-props-readme#40]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/1883/assignments/125676?module_item_id=259663

## What should be changed?

The code provided does not match the lesson code. The lesson code deals with "items" in the state and has a separate function for dispatch actions created. The code provided has "todos" in the state and no function for dispatch actions.

**Comment by ihollander** [comment]
Thanks for flagging this @B0NG0FURY! We made a few changes to this lesson recently in GitHub, and just pushed those changes through to Canvas as well, so you should see the same material in GitHub also reflected in Canvas.
