### ISSUE TITLE
mapDispatchToProps pattern is not always needed at all and is called implicitly.

### ISSUE THREAD

**Issue by yehudamakarov** [learn-co-curriculum/map-dispatch-to-props-readme#5]
Look at https://stackoverflow.com/questions/34458261/how-to-get-simple-dispatch-from-this-props-using-connect-w-redux.

The React Router Nested Routes Lab uses a pattern without mapDispatchToProps and this is possible because the second argument of the connect function will always be passed the dispatch function of the store one way or another.

There is not mention of this pattern here or how it really works. refer to Dan Abramov's answer above where he explains how this works. That info should be made available in this reading.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and included additional information about the different ways to map dispatch to props and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
