### ISSUE TITLE
It's Possible To Pass All Tests Without Correctly Updating The Vote Display

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/map-dispatch-to-props-readme#6]
None of the tests in this lab ensure that after an upvote or downvote action takes place the `QuoteCard` vote display is updated correctly.

**Comment by atxrenegade** [comment]
Could this issue possibly be meant for a different lab?  I dont see a reference to upvote, downvote or a QuoteCard in this lab. Maybe this was directed at a previous version?

**Comment by ecssiah** [comment]
You're right. This comment was meant for the "Cooking With Redux" lab from version 5 of the curriculum. It is a few lessons after this one.

https://learn.co/tracks/full-stack-web-development-v5/redux/redux-library/cooking-with-redux

**Comment by maxwellbenton** [comment]
Hi @ecssiah,

Thank you for opening this issue. We've updated the [`cooking-with-redux`](https://github.com/learn-co-curriculum/quote-maker-react-lab) lab to include additional tests for the `QuoteCard` component, including tests to check if the `QuoteCard` buttons are correctly updating the Redux store, which should resolve this issue.

We apologize for any frustration this may have caused, but we appreciate your feedback and help in ensuring future students will not encounter the same issue.

Thank you for contributing!
