### ISSUE TITLE
No Indicator to add code in the the code examples

### ISSUE THREAD

**Issue by Drewisatlas** [learn-co-curriculum/map-dispatch-to-props-readme#7]
In the past few labs, there have been indicators in the code to show where we are adding or changing the code. This was not the case in this particular lab. It would be nice if these notes were included to easily identify the changes we are making.

**Comment by maxwellbenton** [comment]
Hi @Drewisatlas,

Thank you for providing this feedback. We've updated this lesson to include a bit more detail more code snippets and have added comments to indicate the changes in the code, which should resolve this issue.

We apologize for any confusion this may have caused, but we appreciate your help in making this lesson better for future students!
